### ISSUE TITLE
${HOME}应该是${IAM_CONFIG_DIR}，不然找不到路径

### ISSUE THREAD

**Issue by bubbleboy11** [marmotedu/iam#23]
https://github.com/marmotedu/iam/blob/master/scripts/install/environment.sh#L90

**Comment by colin404** [comment]
> https://github.com/marmotedu/iam/blob/master/scripts/install/environment.sh#L90

这里应该是${HOME}，找不到路径可能是没有生成${HOME}/.iam/cert/admin.pem} 文件。

没有生成的原因要看下。

**Comment by luyees** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
