### ISSUE TITLE
关于 FieldSelector 的疑问

### ISSUE THREAD

**Issue by outer199** [marmotedu/iam#25]
您好。我的疑问是 直接将查询参数拼接到 链接后面(http://aa.com?name=Lisi&age=22) 不就可以了吗？ 为何要单独放在 FieldSelector 字段中呢？有什么优势吗？望赐教

**Comment by xinuxZ** [comment]
个人理解是这样的，不知道是否正确，仅供参考：😁
直接放在链接后面，就要每次自定义struct ，无法达到通用的目的。
1. 每次自定义struct 接收url的query参数，要写较多代码
2. 统一放在FieldSelector中，可以对参数做一些统一的校验（参数类型、大小等）

**Comment by outer199** [comment]
嗯,感谢你的回复.我问了作者大佬. 大佬说 这个是借鉴的 k8s.

**Comment by colin404** [comment]
是的，借鉴的k8s，主要是统一灵活。后面可以根据需要灵活添加需要的查询条件。
