### ISSUE TITLE
关于GenericAPIServer启动的设计问题

### ISSUE THREAD

**Issue by shencw** [marmotedu/iam#40]
老师关于这段代码有两个疑问

https://github.com/marmotedu/iam/blob/28f98f3a6b03d53ba73dd061d8a20115fcfc0e89/internal/pkg/server/genericapiserver.go#L144-L192

1. 这一段代码为啥ping不让它一直自己进行检测，然后用eg.Go去进行处理s.ping方法，如果用这个岂不是可以直接使ping和http、https一起管理如果ping不通则说明服务不可用要关闭么？
2. ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)的context为啥不使用errgroup.WithContext使其保持一致？

**Comment by colin404** [comment]
1. ping 放在eg.Go中就变成异步的了，这里还是希望是同步的，只有ping成功才能继续往下走，不然就报错
2. 这里只是想实现个timeout。errgroup.WithContext 这个不支持Timeout
