### ISSUE TITLE
《从零构建企业级 Go 项目》在哪里能买到，搜索不到呢？

### ISSUE THREAD

**Issue by onlyfew** [marmotedu/iam#41]
如题

**Comment by hanxinhisen** [comment]
> 如题

孔大佬说快出版了，再等等。

**Comment by colin404** [comment]
是的，上半年出版哈

**Comment by gofromzero** [comment]
这书出了吗

**Comment by shencw** [comment]
同问 出了嘛

**Comment by FireSK7** [comment]
还没出

**Comment by colin404** [comment]
京东搜 《企业级Go项目开发实战》就能搜到。感谢支持!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月11日(周六) 凌晨0:34
收件人: ***@***.***&gt;;
抄送: "Lingfei ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [marmotedu/iam] 《从零构建企业级 Go 项目》在哪里能买到，搜索不到呢？ (Issue #41)




 
还没出
