### ISSUE TITLE
目录但单复数问题 

### ISSUE THREAD

**Issue by gaobo0202** [marmotedu/iam#43]

**Comment by colin404** [comment]
建议目录用单数，这只是个约定。


也可以用复数，对项目开发没有任何影响。只要统一规范即刻。


这里建议用单数原因是统一吧，比如：configs可以用复数，但是一些目录复数不是 名词 + s这种格式，这样目录名就不统一了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "marmotedu/iam"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 下午4:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[marmotedu/iam] 目录但单复数问题 (Issue #43)





 
《Go 语言项目开发实战》中提到目录最好用单数，但是在项目中有很多复数的目录（configs, deployments, docs），这部分是什么原因呢？
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
