### ISSUE TITLE
提供的包下载地址似乎失效了

### ISSUE THREAD

**Issue by RushYourMind** [marmotedu/iam#48]
[going@dev iam]$  version=1.1.0 && curl https://marmotedu-1254073058.cos.ap-beijing.myqcloud.com/iam-release/${version}/iam.tar.gz 
<?xml version='1.0' encoding='utf-8' ?>
<Error>
	<Code>UnavailableForLegalReasons</Code>
	<Message>Your account has been banned for the reason of violations, please delete the illegal objects.</Message>
	<Resource>marmotedu-1254073058.cos.ap-beijing.myqcloud.com/iam-release/1.1.0/iam.tar.gz</Resource>
	<RequestId>NjJiZmE1YjZfNGRjZjM4MGJfN2FlZF81NjZkMzRk</RequestId>
	<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTVmYzc0YmEzZDg5YTVjMDA4YzA3ZWY5ZjQwZTE2ZGU1NDIzMTk4YTA3NzNhMmIzMWZhMTNhNWM2NmVmMDc5MmM=</TraceId>
</Error>

**Comment by jitash** [comment]
+1

**Comment by colin404** [comment]
cos没钱了，已充钱，可以下载了
