### ISSUE TITLE
如果定义了错误码常量，这个format有什么意义呢？

### ISSUE THREAD

**Issue by spiritbird** [marmotedu/iam#51]
![image](https://user-images.githubusercontent.com/42992581/183385240-bdbfd0e7-268d-4dc2-915d-1f6a7df64e8d.png)

**Comment by nosbelm** [comment]
你可以跟下代码。

这个是在err中追加一条message。这样你在日志中的error信息中就能看到 'Page not found'

**Comment by colin404** [comment]
可以跟下代码。

这个是在err中追加一条message。这样你在日志中的error信息中就能看到 'Page not found'
