### ISSUE TITLE
请问如何优雅地处理 同时在一个接口或模块使用redis和mysql的情况

### ISSUE THREAD

**Issue by rainbow-xyz** [marmotedu/iam#52]
请问我想根据id获取用户这种类似的操作，需要先查redis代码，如果没有的话，再查mysql数据，还要再更新缓存，这种场景在这个架子里怎么组织代码（service、store）比较合适呢

**Comment by luyees** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by nosbelm** [comment]
```go
type users struct {
    db *gorm.DB
    rdb *redis.Client
}  
```

可以这么来实现，在users struct中再加一个rdb，然后实现你的逻辑

**Comment by colin404** [comment]
```go
type users struct {
    db *gorm.DB
    rdb *redis.Client
}  
```

可以这么来实现，在users struct中再加一个rdb，然后实现你的逻辑
