### ISSUE TITLE
log日志包的扩展

### ISSUE THREAD

**Issue by cyb0225** [marmotedu/iam#53]
使用下来发现日志包可以扩展的几个点：
1.日志包在输出到不同的地方的时候可以采用不同的writer，写到 stdout 的日志可以正常显示颜色，但是写到文本文件里的日志就不能。
我觉得可以用 zap 的tee来拼接多个core实现。
2. 现在的日志我没有找到日志分割的接口，因为是用build来创建 zap 的而不是用 zap.New 的core 来创建的，可以增加适当接口。
3. 对于日期这类我觉得也可以对外提供可选择的接口。

**Comment by nosbelm** [comment]
建议非常棒，后面考虑实现这个特性，我先记录到TODO List中。或者你可以实现提个PR

**Comment by colin404** [comment]
建议非常棒，后面考虑实现这个特性，我先记录到TODO List中。或者你可以实现提个PR
