### ISSUE TITLE
Makefile中的install.install是否应该移除?

### ISSUE THREAD

**Issue by leilei3167** [marmotedu/iam#59]
```
## install: Install iam system with all its components.
.PHONY: install
install:
	@$(MAKE) install.install

```
`install.install`并未在其他的文件中被定义,是否需要将其删除?或者新增一个`install.mk`文件,在其中定义执行自动安装项目的target逻辑?

**Comment by nosbelm** [comment]
感谢反馈，之前放上去是因为想实现install.mk，后来没有实现，我先移除了

**Comment by colin404** [comment]
感谢反馈，之前放上去是因为想实现install.mk，后来没有实现，我先移除了
