### ISSUE TITLE
飞哥选型ladon的原因可以透露一下吗

### ISSUE THREAD

**Issue by h1deOnBush** [marmotedu/iam#64]
为啥不用像casbin这种star数更高的库

**Comment by nosbelm** [comment]
建议使用casbin。当时选型ladon知识觉得ladon比较简单，适合用来作为教学。

iam核心目的是教学：如何进行Go项目。而非业务功能本身。所以在IAM中，你会发现一些设计是为了教学而强行塞进去的，例如：为了介绍如何开发异步任务，强行虚构了一个禁止用户登录的功能；

**Comment by hsluoyz** [comment]
Hi，我是来自Casbin团队的，Casbin应该是目前go领域最主流、功能最为强大的权限库。希望能够和咱们教程合作，我们可以提供各种技术支持~

**Comment by nosbelm** [comment]
大佬，可以的，我有个新的教程，就是用了casbin。

**Comment by colin404** [comment]
> 假期自动回复邮件。您好，我最近正在休

建议使用casbin。当时选型ladon知识觉得ladon比较简单，适合用来作为教学。

iam核心目的是教学：如何开发Go项目。而非业务功能本身。所以在IAM中，你会发现一些设计是为了教学而强行塞进去的，例如：为了介绍如何开发异步任务，强行虚构了一个禁止用户登录的功能；
