### ISSUE TITLE
Uninstall should be install

### ISSUE THREAD

**Issue by litaaron** [marmotedu/iam#9]
The following two lines should be corrected with install not uninstall in iam/docs/guide/zh-CN/installation/04_install_iam.md 

cd /tmp/iam && ./scripts/install/iamctl.sh iam::iamctl::uninstall  -->cd /tmp/iam && ./scripts/install/iamctl.sh iam::iamctl::install
cd /tmp/iam && ./scripts/install/man.sh iam::man::uninstall  -->cd /tmp/iam && ./scripts/install/man.sh iam::man::install

![Uninstall issues](https://user-images.githubusercontent.com/5482649/126119459-8c0fdb7c-e2c0-4d0b-bdc7-4be2e6111b09.png)

**Comment by colin404** [comment]
thanks for your issue

**Comment by colin404** [comment]
already fix at bd54b8b5a03935d7eb90fd8fd7063738c627fb29
